### ISSUE TITLE
Persistence Through Updates

### ISSUE THREAD

**Issue by BungyStudios** [paveloom-f/lbry-desktop#17]
OTA updates resets the app to stock functionality.

Recommended to rewrite updater in app to download from this repository rather than official LBRY repository.

**Comment by Paveloom** [comment]
I've added the `electron-updater`'s artifacts to the last two releases, they will be ready in a few minutes. The application should grab those instead of the official ones when checking for updates.

You can check if it works by downloading the [`v0.51.1`](https://github.com/paveloom-f/lbry-desktop/releases/tag/v0.51.1) release (when it's ready) and allowing it to self-update.

**Comment by Paveloom** [comment]
The releases are ready now. I urge you to test it and report if something goes wrong. If everything's okay, you may close this issue.

**Comment by BungyStudios** [comment]
Thank you so much! Are there any other known filters aside from the DMCA? I'm interested to know.

**Comment by Paveloom** [comment]
I guess the only other filter is illegal content (read the content policy [here](https://lbry.com/faq/content)).

That's not documented, but they have two lists of outpoints they query in the official binaries:

- https://api.lbry.io/file/list_blocked
- https://api.lbry.io/file/list_filtered
